/* pilrc generated file.  Do not edit!*/
#define UnknownCardAlert 1054
#define NonWritableCardAlert 1053
#define NoCardAlert 1052
#define DescAlert 1045
#define FileAlert 1044
#define DelAlert 1043
#define fldTitle 1042
#define btnDetailDel 1041
#define btnDetailCancel 1040
#define btnDetailOk 1039
#define DetailForm 1038
#define bmpRecord 1037
#define bmpStop 1036
#define MemAlert 1035
#define bmpSdCard 1034
#define bmpInternal 1033
#define sldSndQal 1031
#define sldRecVol 1028
#define sldSndVol 1027
#define btnPFSave 1026
#define btnPFCancel 1025
#define chkUseCard 1024
#define PrefForm 1023
#define AboutOKButton 1019
#define AboutForm 1018
#define btnStop 1017
#define bmpPlay 1016
#define btnPlay 1015
#define btnRecord 1014
#define lstRecordings 1013
#define MainForm 1012
#define RomIncompatibleAlert 1011
#define EditOnlyMenuBar 1009
#define OptionsAboutSoundRec 1008
#define mnuPrefs 1006
#define mnuDelete 1005
#define mnuExport 1003
#define mnuDetails 1002
//
// Autogenerated symbols - 6/9/2004 9:24:53 PM
// Falch.net PilRC Designer
//
#define MainMenuBar 1001
//
// Autogenerated symbols - 6/14/2004 10:43:07 AM
// Falch.net PilRC Designer
//
#define	chkOneButton	1004
//
// Autogenerated symbols - 6/16/2004 12:58:22 PM
// Falch.net PilRC Designer
//
#define	btnPause	1002
//
// Autogenerated symbols - 6/16/2004 1:02:24 PM
// Falch.net PilRC Designer
//
#define	chkBeep	1005
//
// Autogenerated symbols - 6/16/2004 1:04:51 PM
// Falch.net PilRC Designer
//
#define	RecPrefForm	1005
#define	btnRPFCancel	1006
//
// Autogenerated symbols - 6/16/2004 1:06:43 PM
// Falch.net PilRC Designer
//
#define	btnRPFSave	1007
#define	OneBPrefForm	1006
#define	btnOBPFCancel	1007
//
// Autogenerated symbols - 6/16/2004 1:33:41 PM
// Falch.net PilRC Designer
//
#define	btnOBPFSave	1008
#define	mnuRecPrefs	1004
//
// Autogenerated symbols - 6/18/2004 1:17:44 PM
// Falch.net PilRC Designer
//
#define	mnuOBPrefs	1007
//
// Autogenerated symbols - 6/18/2004 1:46:13 PM
// Falch.net PilRC Designer
//
#define	chkOBAfterReset	1009
#define	lblAlarmDate	1005
#define	lblAlarmTime	1006
#define	lblAlarm	1007
#define	chkAlarm	1008
#define	tgrAlarmDate	1009
//
// Autogenerated symbols - 6/24/2004 3:30:46 PM
// Falch.net PilRC Designer
//
#define	tgrAlarmTime	1010
//
// Autogenerated symbols - 6/25/2004 1:14:06 PM
// Falch.net PilRC Designer
//
#define	tgrActButton	1010
#define	lblLength	1011
//
// Autogenerated symbols - 6/29/2004 2:48:05 PM
// Falch.net PilRC Designer
//
#define	lblSize	1012
#define	NewTrigger	1010
//
// Autogenerated symbols - 6/29/2004 2:48:43 PM
// Falch.net PilRC Designer
//
#define	NewList	1011
#define	tgrOneButton	1011
#define	lstOneButton	1012
